#‘#’后为注释；当前配置文件编码为UTF-8编码
#注意：修改键名称会使程序运行出错，
#格式：键=值

# 开机启动，1是，0否
开机启动 = 0

# 延时启动,已废弃（勿删此键值）
自启延时 = 5

#------远程操作------
远程密码 = 123

隐藏文件夹 = 0
#------远程操作------

#------MQTT------
#是否使用MQTT上报数据
MQTT使能 = 0

#客户端ID
ID = mqttx_388cab6688

#ssl/tls加密，0停用，1启用
#是否使用加密=1
是否使用加密 = 0

#主题
发布主题 = /sys/mqttx_388cab12/post
订阅主题 = /sys/mqttx_388cab12/pub

#服务端地址
#地址 = broker.emqx.io
地址 = www.icsteam.cn
#地址=127.0.0.1
#根据需要可修改端口号
#端口=8883
端口 = 1883

#需要时使用
#账户 = abc
#密码 = 123

#mqtt上报间隔，秒
上报间隔 = 5
#上报格式模板 @@@会替换成要上报的字典数据，除@@@之外字符的可以任意修改,必须是json格式，{"properties":@@@}:
上报格式模板 = {"properties":@@@}

#接收下发模板（写死了，不起作用）
下发格式模板 = {"SetProperty":@@@}
#------MQTT------

#------Snap7------
#控制器地址，端口默认102

#每个plc一个参数列表，多个plc参数用逗号隔开,ID唯一不重复
#plc参数列表说明(plc地址,modbus ID（唯一）,plc名称(唯一),点位文件路径csv，plc机架号，plc卡槽号【200smart、1200和1500使用机架号和卡槽号使用0，0即可】)
控制器参数 = [
           #('127.0.0.1',1,'plc1','ztest.csv',0,0),  # 1号配置
			('127.0.0.1',1,'SR20','ztest.csv',0,0),  # 自用PLC
			#('127.0.0.2',2,'SR21','ztest.csv',0,0),  # 自用PLC
			# ('192.168.1.88',1,'plc1','xr.csv',0,0),  # 3号配置
			#('192.168.2.11',1,'plc1','plc1.csv',0,0),  # 4号配置
            ]
#读控制器频率，单位秒;1个plc读2000个字节内，读5个plc，1秒内
读取频率 = 0.4
#------Snap7------

#------Modbus_Tcp------
#是否使用Modbus_Tcp服务端功能，1使用，0停用
mbtcp使能 = 1
#Modbus_Tcp服务端地址，地址默认：127.0.0.1
mbtcp地址 = 0.0.0.0
#Mobus_Tcp服务端端口
mbtcp端口 = 502
#------Modbus_Tcp------

#------web_api------
# 获取数据地址http://webApi地址:端口/get
# 设置数据地址http://webApi地址:端口/post
# 数据上报与下发格式与mqtt一致
webApi使能 = 1
webApi地址 = 0.0.0.0
webApi端口 = 5000
#------web_api------

#------iec104------
iec104使能 = 1
iec104地址 = 0.0.0.0
iec104端口 = 2404
iec104站地址 = 1
#------iec104------

#------点位归档设置------
归档使能 = 1
# 单位秒
归档周期 = 5

#------数据查询服务---
数据查询服务使能 = 1
数据查询服务地址 = 0.0.0.0
数据查询服务端口 = 5008